export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const REMOVE_COMPLETED_TODOS = 'REMOVE_COMPLETED_TODOS';
export const COMPLETE_TODO_SUCCESS = 'COMPLETE_TODO_SUCCESS';
export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const SET_MESSAGE = 'SET_MESSAGE';

export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const GET_USERS = 'GET_USERS';